config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'miscellaneous#index'
  get '/dashboard' => 'miscellaneous#dashboard'
  get '/connect' => 'connect#index'
  post '/sendtext' => 'send_text#create'

  resources :users do
    resources :submissions
  end

                         
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :submissions
  has_many :contacts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/concerns/connect_controller.rb
class ConnectController < ApplicationController

  def index
  end

end

app/controllers/miscellaneous_controller.rb
class MiscellaneousController < ApplicationController

  skip_before_action :authenticate_user!, only: :index

  def index
    @home_page = true
    if current_user
      redirect_to '/dashboard'
    end
  end

  def dashboard
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :contact1_name, :contact1_number, :contact2_name, :contact2_number)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password, :contact1_name, :contact1_number, :contact2_name, :contact2_number)
  end
  
end

app/controllers/send_text_controller.rb
class SendTextController < ApplicationController

  def index
  end

  def create
    name = current_user.name
    contact1_number = current_user.contact1_number
    contact2_number = current_user.contact2_number

    twilio_sid = ENV['TWILIO_SID']
    twilio_token = ENV['TWILIO_TOKEN']
    twilio_phone_number = ENV['TWILIO_NUMBER']

    @client = Twilio::REST::Client.new twilio_sid, twilio_token

    @client.messages.create(
      :from => "#{twilio_phone_number}",
      :to => "+1#{contact1_number}",
      :body => "Hi, it's #{name}. I am sending you a text via Take a Breather. I am feeling distressed and would like to be in touch with you as soon as possible."
    )

    @client.messages.create(
      :from => "#{twilio_phone_number}",
      :to => "+1#{contact2_number}",
      :body => "Hi, it's #{name}. I am sending you a text via Take a Breather. I am feeling distressed and would like to be in touch with you as soon as possible."
    )

    redirect_to connect_path
  end

end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

  def index
    @submissions = Submission.all
  end

  def show
    @submission = Submission.find(params[:id])
    @form_path = user_submission_path
  end

  def new
    @submission = Submission.new
    @form_path = user_submissions_path
  end

  def create
    @submission = current_user.submissions.build(submission_params)
    remove_string = params[:submission][:feeling].shift
    @submission.feeling = params[:submission][:feeling].join(',')
    # @submission.user_id = current_user.id
    if @submission.save
      redirect_to user_submission_path(user_id: current_user.id, id: @submission.id)
    else 
      redirect_to :action => 'index'
    end
  end

  def edit
    @submission = Submission.find(params[:id])
    @form_path = user_submission_path
  end

  def update
    @submission = Submission.find(params[:id])
    remove_string = params[:submission][:feeling].shift
    @submission.feeling = params[:submission][:feeling].join(',')
    @submission.update(submission_params)
    redirect_to user_submission_path(user_id: current_user.id, id: @submission.id)
  end

  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy
    redirect_to user_submissions_path
  end

  private

  def submission_params
    params.require(:submission).permit(:date, :location, :feeling, :conflict, :letter)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/connect/index.html.erb
<div id="dashboard-logo">Take a Breather</div>

<div id="main-container">

  <div id="circle-container">
    <div class="greyed">
      <div class="circle-star">&#10036;</div>
      <div class="circle-text-greyed"><%= link_to "Share", new_user_submission_path(current_user), class: "circle-text-greyed" %></div>
      <div class="circle-info">Create new entry</div>
    </div>
    <div class="greyed">
      <div class="circle-star">&#10036;</div>
      <div class="circle-text-greyed"><%= link_to "Reflect", user_submissions_path(current_user), class: "circle-text-greyed" %></div>
      <div class="circle-info">View past entries</div>
    </div>
    <div id="circle3">
      <div class="circle-star" style="color: #c8995a">&#10036;</div>
      <div class="circle-text"><%= link_to "Connect", connect_path, class: "link" %></div>
      <div class="circle-info">Find resources</div>
    </div>
  </div>

  <div id="display-container-yellow">
    <div id="x-background-yellow"><%= link_to 'X', root_path, class: 'home-link' %></div>
    <p id="display-message">Support Circle</p>
    <p class="display-text">I am in distress and would like to reach out to my main contacts.</p>
    <%= link_to "Send Text", sendtext_path, method: 'POST', class: 'send-text-btn' %><br><br>
    <p class="display-text">For the national suicide hotline, <br> please call 1-800-273-TALK.</p>
    <p class="display-text">Or, call 211 for the following services:
      <ul class="display-text">
        <li>Basic human needs resources;</li>
        <li>Physical & mental health resources;</li>
        <li>Work support;</li>
        <li>Support for senior citizens and persons with disabilities;</li>
        <li>Support for children, youth, and families.</li>
      </ul>
    </p>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Breatherapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Nunito:400,300,700|Roboto+Slab:400,300,700' rel='stylesheet' type='text/css'>
<body data-no-turbolink>
  <div id="wrapper">

    <div id="content">
      <% if user_signed_in? %>
        <p class="navbar-text">
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Log out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        </p>
      <% end %>
      <%= yield %>
      <body class="<%= @home_page ? 'homepage' : '' %>">
    </div>

    <div id="footer">
      <p id="footer-text">&copy; 2015 Take a Breather &#9996; Made by <a href="http://www.twitter.com/MalinaTran">@MalinaTran</a></p>
    </div>

  </div>
</body>
</html>

app/views/miscellaneous/dashboard.html.erb
<div id="dashboard-logo">Take a Breather</div>

<div id="main-container">

  <div id="circle-container">
    <div id="circle1">
      <div class="circle-star">&#10036;</div>
      <div class="circle-text"><%= link_to "Share", new_user_submission_path(current_user), class: "link" %></div>
      <div class="circle-info">Create new entry</div>
    </div>
    <div id="circle2">
      <div class="circle-star">&#10036;</div>
      <div class="circle-text"><%= link_to "Reflect", user_submissions_path(current_user), class: "link" %></div>
      <div class="circle-info">View all entries</div>
    </div>
    <div id="circle3">
      <div class="circle-star">&#10036;</div>
      <div class="circle-text"><%= link_to "Connect", connect_path, class: "link" %></div>
      <div class="circle-info">Find resources</div>
    </div>
  </div>

  <div id="display-container">
    <div id="display-quote">
      <q>Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.</q><br>&mdash;
    </div>
    <br>
    <p class="display-text">1,2, and breathe. Experiencing emotions is human. But sometimes, it may feel uncomfortable or disempowering.</p> 
    <p class="display-text">Welcome to a safe and secure space where you can work through your feelings and identify resources as you navigate your situation.</p>
    <p class="display-text">We wish you all the best!</p>
    <p class="display-text">– The Take a Breather Team</p>
  </div>

</div>

app/views/miscellaneous/index.html.erb
<div id="splash-container">
  <div id="splash-logo">Take a Breather</div>
  <div id="splash-lead">1, 2, and Breathe</div>
  <div id="splash-text">
    Your safe space for when you need it the most. Express your emotions, reach out to friends and family members, and find resources to help navigate your situation. We are helping you help yourself, so that you can thrive.
  </div>
  <%= link_to "Sign up", new_user_registration_path, :class => 'splash-btn'  %>
  <%= link_to "Log in", new_user_session_path, :class =>  'splash-btn'  %>
</div>

app/views/submissions/_form.html.erb
<div id="form-container">

  <%= form_for(@submission, url: @form_path) do |f| %>

    <div class="field-container">
      <div class="field"><span class="form-num">1.</span> <%= f.text_field :date, :placeholder => 'Enter today\'s date' %></div>
    </div>

    <div class="field-container">
      <div class="field"><span class="form-num">2.</span> <%= f.text_field :location, class: 'location-field' %></div>
    </div>

    <div class="field-container"> 
      <div class="label"><span class="form-num">3.</span> How are you feeling today? (To select multiple, hold down the ⌘ button in Mac or ctrl button in Windows).</div>
      <div class="emotion_list"><%= f.select(:feeling, [['Angry/frustrated', 'Angry/frustrated'], ['Anxious', 'Anxious'], ['Helpless', 'Helpless'], ['Humiliated', 'Humiliated'], ['Sad/upset/depressed', 'Sad/upset/depressed'], ['Stressed', 'Stressed'], ['Undervalued', 'Undervalued']], {}, { :multiple => true, :size => 5} ) %></div>
      </div>

    <div class="field-container">
      <div class="label"><span class="form-num">4.</span> Who are you experiencing conflict with?</div>
      <div class="conflict_list"><%= f.select(:conflict, options_for_select(['Myself','My partner','My parents', 'Sibling', 'Other family member','Friend or acquaintance','Stranger','Colleague or coworker', 'Other'], @submission.conflict), include_blank: true ) %></div>
    </div>

    <div class="field-container">
      <div class="label"><span class="form-num">5.</span> Write a letter to anyone you'd like.</div>
      <div class="letter"><%= f.text_area :letter %></div>
    </div>

    <div class="field-container">
      <%= f.submit 'Submit', class: 'submit-btn' %>
    </div>

  <% end %>

</div>

app/views/submissions/edit.html.erb
<div id="dashboard-logo">Take a Breather</div>

<div id="main-container">

  <div id="circle-container">
    <div class="greyed">
      <div>
        <div class="circle-star">&#10036;</div>
        <div class="circle-text-greyed"><%= link_to "Share", new_user_submission_path(current_user), class: "circle-text-greyed" %></div>
        <div class="circle-info">Create new entry</div>
      </div>
    </div>
    <div id="circle2">
      <div class="circle-star" style="color: #c8995a">&#10036;</div>
      <div class="circle-text"><%= link_to "Reflect", user_submissions_path(current_user), class: "link" %></div>
      <div class="circle-info">View past entries</div>
    </div>
    <div class="greyed">
      <div>
        <div class="circle-star">&#10036;</div>
        <div class="circle-text-greyed"><%= link_to "Connect", connect_path, class: "circle-text-greyed" %></div>
        <div class="circle-info">Find resources</div>
      </div>
    </div>
  </div>

  <div id="display-container-orange">
    <%= link_to 'X', root_path, class: 'home-link' %>
    <%= render :partial => 'form' %>
  </div>

</div>

app/views/submissions/index.html.erb
<div id="dashboard-logo">Take a Breather</div>

<div id="main-container">

  <div id="circle-container">
    <div class="greyed">
      <div class="circle-star">&#10036;</div>
      <div class="circle-text-greyed"><%= link_to "Share", new_user_submission_path(current_user), class: "circle-text-greyed" %></div>
      <div class="circle-info">Create new entry</div>
    </div>
    <div id="circle2">
      <div class="circle-star" style="color: #c8995a">&#10036;</div>
      <div class="circle-text"><%= link_to "Reflect", user_submissions_path(current_user), class: "link" %></div>
      <div class="circle-info">View past entries</div>
    </div>
    <div class="greyed">
      <div class="circle-star">&#10036;</div>
      <div class="circle-text-greyed"><%= link_to "Connect", connect_path, class: "circle-text-greyed" %></div>
      <div class="circle-info">Find resources</div>
    </div>
  </div>

  <div id="display-container-orange">
    <%= link_to 'X', root_path, class: 'home-link' %>
    <p id="display-message">All Entries</p>
    <table>
      <tbody>
        <% @submissions.each do |entry| %>
        <tr>
          <td class="date"><%= entry.date.try(:strftime, "%a | %b %-d, %Y") %></td>
          <td class="action"><%= link_to 'View', user_submission_path(current_user.id, entry.id), class: 'view-link' %></td>
          <td class="action"><%= link_to 'Edit', edit_user_submission_path(current_user.id, entry.id), class: 'edit-link' %></td>
          <td class="action"><%= link_to 'Delete', user_submission_path(current_user.id, entry.id), :method => 'delete', class: 'delete-link' %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/submissions/new.html.erb
<div id="dashboard-logo">Take a Breather</div>

<div id="main-container">

  <div id="circle-container">
    <div id="circle1">
      <div class="circle-star" style="color: #c8995a">&#10036;</div>
      <div class="circle-text"><%= link_to "Share", new_user_submission_path(current_user), class: "link" %></div>
      <div class="circle-info">Create new entry</div>
    </div>
    <div class="greyed">
      <div class="circle-star">&#10036;</div>
      <div class="circle-text-greyed"><%= link_to "Reflect", user_submissions_path(current_user), class: "circle-text-greyed" %></div>
      <div class="circle-info">View past entries</div>
    </div>
    <div class="greyed">
      <div class="circle-star">&#10036;</div>
      <div class="circle-text-greyed"><%= link_to "Connect", connect_path, class: "circle-text-greyed" %></div>
      <div class="circle-info">Find resources</div>
    </div>
  </div>

  <div id="display-container-pink">
    <%= link_to 'X', root_path, class: 'home-link' %>
    <%= render :partial => 'form' %>
  </div>

  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyC3oUAlkb1W-g1FW-V_P0SfvbnMsiwLe98&signed_in=true&libraries=places&callback=initMap" %>
</div>

app/views/submissions/show.html.erb
<div id="dashboard-logo">Take a Breather</div>

<div id="main-container">

  <div id="circle-container">
    <div class="greyed">
      <div class="circle-star">&#10036;</div>
      <div class="circle-text-greyed"><%= link_to "Share", new_user_submission_path(current_user), class: "circle-text-greyed" %></div>
      <div class="circle-info">Create new entry</div>
    </div>
    <div id="circle2">
      <div class="circle-star" style="color: #c8995a">&#10036;</div>
      <div class="circle-text"><%= link_to "Reflect", user_submissions_path(current_user), class: "link" %></div>
      <div class="circle-info">View past entries</div>
    </div>
    <div class="greyed">
      <div class="circle-star">&#10036;</div>
      <div class="circle-text-greyed"><%= link_to "Connect", connect_path, class: "circle-text-greyed" %></div>
      <div class="circle-info">Find resources</div>
    </div>
  </div>

  <div id="display-container-orange">
    <%= link_to 'X', root_path, class: 'home-link' %>

    <p id="display-message"><%= @submission.date.try(:strftime, "%a | %b %-d, %Y") %></p>

    <div id="button-container">
      <%= link_to 'Edit', edit_user_submission_path, class: 'edit-btn' %>
      <%= link_to 'Delete', user_submission_path, :method => 'delete', class: 'delete-btn' %>
      <%= link_to 'All Entries', user_submissions_path, class: 'all-entries-btn' %>
    </div>

    <div class="field-container">
      <div class="show-label">I was located at</div>
      <div class="show-field"><%= @submission.location %></div>
    </div>

    <div class="field-container">
      <div class="show-label">Feelings</div>
      <div class="show-field"><%= @submission.feeling.split(',').join(', ') %></div>
    </div>

    <div class="field-container">
      <div class="show-label">I was experiencing conflict mainly with</div>
      <div class="show-field"><%= @submission.conflict %></div>
    </div>

    <div class="field-container">
      <div class="show-label">My letter of reflection</div>
      <div class="show-field"><%= @submission.letter %></div>
    </div>

  </div>

</div>